name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - name: npm ci
        run: npm ci
      - name: run lint
        run: npm run lint
  build:
    name: run build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - name: npm ci
        run: npm ci
      - name: run build
        run: npm run build
