name: automatic publish

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: release
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-repo
      - run: pnpm run build
      - name: release
        run: pnpm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
